import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <header className="bg-gray-50 shadow-sm flex justify-between p-5">
          <h1>LOGO</h1>
          <nav className="flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/posts">Posts</Link>
            <Link href="/avatars">Avatars</Link>
          </nav>
        </header>

        {children}

        <footer className="bg-gray-50 shadow-sm w-full text-center p-5 fixed bottom-0">
          © 2024 Demo, Inc.
        </footer>
      </body>
    </html>
  );
}
